create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  name text not null,
  age integer not null check (age between 1 and 120),
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  exercise text not null,
  repetitions integer not null default 0,
  avg_angle double precision not null default 0,
  max_range double precision not null default 0,
  form_score double precision not null default 0,
  feedback text,
  created_at timestamptz not null default now()
);

alter table public.patients enable row level security;
alter table public.sessions enable row level security;

-- This demo policy allows anonymous app users to read/write project records.
-- For real patient/medical data, replace this with authenticated, user-scoped policies.
drop policy if exists "demo patients select" on public.patients;
drop policy if exists "demo patients insert" on public.patients;
drop policy if exists "demo sessions select" on public.sessions;
drop policy if exists "demo sessions insert" on public.sessions;

create policy "demo patients select" on public.patients for select to anon using (true);
create policy "demo patients insert" on public.patients for insert to anon with check (true);
create policy "demo sessions select" on public.sessions for select to anon using (true);
create policy "demo sessions insert" on public.sessions for insert to anon with check (true);
